# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version = 1.21.1
parchment_version = 2024.11.17
# Base Dependencies
minecraft_version = 1.21.1
minecraft_version_range=[1.21.1]

neo_version = 21.1.129
neo_version_range=[21.1.129,)
loader_version_range=[4,)


mod_version=1.8.0
mod_id=melter

mod_author=oierbravo
mod_name=Melter
mod_group_id=com.oierbravo.melter
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=oierbravo
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=A simple melter block that turn blocks into liquid.
mod_license=MIT

create_version = 6.0.4-53
flywheel_minecraft_version = 1.21.1
flywheel_version = 1.0.2
registrate_version = MC1.21-1.3.0+62
ponder_version = 1.0.46



jade_id = 5591256
jei_minecraft_version = 1.21.1
jei_version = 19.21.0.247

#curios_minecraft_version = 1.20.1
#curios_version = 5.2.0

kubejs_version=2100.7.0-build.116
rhino_version=2100.2.5-build.41
architectury_version=13.0.2

#jade_id = 4654448

ct_enabled = true
ct_minecraft_version = 1.21.1
ct_version = 20.0.21
ct_annotation_processor_version = 3.0.0.16
#ct_create_version =  3.0.0.6

curseforge_id = 679027
modrinth_id = 1oFTujWR